### ISSUE TITLE
Max result filter seems to limit search instead of results

### ISSUE THREAD

**Issue by Zoopah** [conduktor/conduktor-platform#157]
When using conduktor console and a JS filter on a specific header (return headers['xxx'] == '8d8eeb49-ef8a-491e-83a7-d6615bb68060'), I need to set the max result filter to 2000 to receive 1 result. If I set it to 1000, I receive no results. 

It looks like the max result filter limits the searched items, and not the results.

![image](https://github.com/conduktor/conduktor-platform/assets/22501077/dbe2e265-8d6c-4d79-b218-6ca72521da36)

vs

![image](https://github.com/conduktor/conduktor-platform/assets/22501077/012b3d25-03ef-452e-a93a-06e9691e08b5)

**Comment by twobeeb** [comment]
Hi, 
You are correct, 
JS Filters are applied before Max Results **except** when Show From Most Recent where the JS Filter is applied after polling the X most recent. 
This is because we don't have a true backward search implemented.
Try using a forward search by changing the Show From to any other choice.

Check our documentation for more details: https://docs.conduktor.io/platform/console/features/browse-data/

**Comment by Zoopah** [comment]
Thanks for getting back on this.

If that's working as intended then it's a tad confusing. All I say is that in an ideal world, it might perhaps be an idea to rename 'Max results' to something like 'Max searched items' when the Show from Most recent is selected? 

We'll take this flow in mind on our side in the future.

Closing the issue.

**Comment by Zoopah** [comment]
I really can't tell... I feel like combing "Most recent" with other options in the same dropdown while this selection can impact functionality in another dropdown might not be the way the go and will always be confusing..? ...but I'm not a UX guy :)
