### ISSUE TITLE
UI FR: open topic/consumer/resource group in new tab

### ISSUE THREAD

**Issue by JohnPreston** [conduktor/conduktor-platform#58]
Hello

A bit of UX feedback related to the UI.

Currently, I cannot use the filter to list a set of topics, and then do 'open to new tab' (right click or middle click option).
And when I open 1 topic, then go back (previous page) the filter is also gone so I have to start over again.

Can we please get open to the new tab and/or maintain the filter value? The new tab one would be a great good first feature to have.

Thank you!

**Comment by guizmaii** [comment]
Hey @JohnPreston,

Thanks for your feedback 🙂

In the latest version of Console, we now put your search value in the URL so that it's easier for you to share your search with your colleagues. It also allows you to duplicate your browser tab and land on the same table as your original tab

![quick-search-url](https://user-images.githubusercontent.com/1193670/197021254-6123ef6b-f933-4c7a-8694-97454e2bb40b.png)

We hope that it's solving your issue.

Cheers,
Jules

**Comment by rokh-conduktor** [comment]
fixed in 1.1.3
